//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterSimUI.UserControls {
    
    
    public partial class PriorOutputsUserControl {
        
        /// <summary>
        /// POUCOutputControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.OutputUserControl POUCOutputControl1;
        
        /// <summary>
        /// POUCOutputControl1a control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.OutputUserControl POUCOutputControl1a;
        
        /// <summary>
        /// POUCOutputControl2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.OutputUserControl POUCOutputControl2;
        
        /// <summary>
        /// POUCOutputControl2a control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.OutputUserControl POUCOutputControl2a;
        
        /// <summary>
        /// POUCOutputControl3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.OutputUserControl POUCOutputControl3;
        
        /// <summary>
        /// OutputUserControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.OutputUserControl OutputUserControl1;
        
        /// <summary>
        /// OutputUserControl2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.OutputUserControl OutputUserControl2;
        
        /// <summary>
        /// OutputUserControl3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.OutputUserControl OutputUserControl3;
        
        /// <summary>
        /// OutputUserControl4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.OutputUserControl OutputUserControl4;
        
        /// <summary>
        /// OutputUserControl5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.OutputUserControl OutputUserControl5;
        
        /// <summary>
        /// POUCOutputControl7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.OutputUserControl POUCOutputControl7;
        
        /// <summary>
        /// POUCOutputControl5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.OutputUserControl POUCOutputControl5;
        
        /// <summary>
        /// POUCOutputControl8B control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.OutputUserControl POUCOutputControl8B;
        
        /// <summary>
        /// POUCOutputControl8C control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.OutputUserControl POUCOutputControl8C;
        
        /// <summary>
        /// OutputUserControl6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.OutputUserControl OutputUserControl6;
        
        /// <summary>
        /// OutputUserControl7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.OutputUserControl OutputUserControl7;
        
        /// <summary>
        /// OutputUserControl8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.OutputUserControl OutputUserControl8;
        
        /// <summary>
        /// OutputUserControl9 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.OutputUserControl OutputUserControl9;
        
        /// <summary>
        /// POUCOutputControl9 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.OutputUserControl POUCOutputControl9;
        
        /// <summary>
        /// POUCOutputControl13 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.OutputUserControl POUCOutputControl13;
        
        /// <summary>
        /// POUCOutputControl10 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.OutputUserControl POUCOutputControl10;
        
        /// <summary>
        /// POUCOutputControl11 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.OutputUserControl POUCOutputControl11;
        
        /// <summary>
        /// OutputControl18 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.OutputUserControl OutputControl18;
        
        /// <summary>
        /// OutputUserControl10 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.OutputUserControl OutputUserControl10;
        
        /// <summary>
        /// OutputUserControl11 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.OutputUserControl OutputUserControl11;
        
        /// <summary>
        /// OutputUserControl12 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.OutputUserControl OutputUserControl12;
        
        /// <summary>
        /// OutputUserControl13 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.OutputUserControl OutputUserControl13;
        
        /// <summary>
        /// OutputUserControl14 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.OutputUserControl OutputUserControl14;
    }
}
